from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)

# ==========================================================
# PDF Generator
# ==========================================================

class PDFGenerator:

    def __init__(self):

        self.styles = getSampleStyleSheet()

        self.title_style = self.styles["Heading1"]
        self.title_style.alignment = TA_CENTER
        self.title_style.textColor = colors.darkblue
        self.title_style.spaceAfter = 15

        self.heading_style = self.styles["Heading2"]
        self.heading_style.textColor = colors.darkblue
        self.heading_style.spaceBefore = 10
        self.heading_style.spaceAfter = 8

        self.normal_style = self.styles["BodyText"]

        self.degree_style = self.styles["Heading3"]

        self.degree_style.alignment = TA_CENTER

        self.degree_style.textColor = colors.white

        self.degree_style.spaceAfter = 0

        self.degree_style.spaceBefore = 0

    # ======================================================
    # Table Style
    # ======================================================

    def table_style(self, header_color):

        return TableStyle([
            ("BACKGROUND", (0,0), (-1,0), header_color),
            ("TEXTCOLOR", (0,0), (-1,0), colors.white),
            ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
            ("FONTSIZE", (0,0), (-1,0), 11),
            ("BOTTOMPADDING", (0,0), (-1,0), 8),
            ("GRID", (0,0), (-1,-1), 0.5, colors.grey),
            ("BOX", (0,0), (-1,-1), 1, colors.black),
            ("BACKGROUND", (0,1), (-1,-1), colors.whitesmoke),
            ("ALIGN", (0,0), (-1,-1), "CENTER"),
            ("VALIGN", (0,0), (-1,-1), "MIDDLE"),
        ])
    

    def add_footer(self, canvas, doc):
        canvas.saveState()
        canvas.setFont("Helvetica",8)
        canvas.setFillColor(colors.grey)

        canvas.drawRightString(
            550,
            30,
            "Generated by : Student Grade Management System"
        )

        canvas.restoreState()


    # ======================================================
    # Generate PDF
    # ======================================================

    def generate_student_report(self, report):

        buffer = BytesIO()

        doc = SimpleDocTemplate(
            buffer,
            pagesize=(8.27 * inch, 11.69 * inch),
            rightMargin=30,
            leftMargin=30,
            topMargin=30,
            bottomMargin=30
        )

        elements = []

        # -----------------------------------------------
        # Title
        # -----------------------------------------------

        elements.append(
            Paragraph(
                "STUDENT REPORT",
                self.title_style
            )
        )

        elements.append(
            Spacer(1,20)
        )






        # ==================================================
        # PERSONAL DETAILS
        # ==================================================

        elements.append(
            Paragraph(
                "PERSONAL DETAILS",
                self.heading_style
            )
        )

        student = report["student"]
        personal_data = [
            [
                "<b>Name</b>", student.name,
                "<b>Gender</b>", student.gender
            ],

            [
                "<b>Father Name</b>", student.father_name,
                "<b>Mother Name</b>", student.mother_name
            ],

            [
                "<b>Date of Birth</b>", str(student.date_of_birth),
                "<b>Phone</b>", student.phone
            ],

            [
                "<b>Email</b>", student.email,
                "<b>Address</b>", student.address
            ]
        ]

        personal_table = Table(
            [
                [
                    Paragraph(row[0], self.normal_style),
                    Paragraph(str(row[1]), self.normal_style),
                    Paragraph(row[2], self.normal_style),
                    Paragraph(str(row[3]), self.normal_style)
                ]
                for row in personal_data
            ],
            colWidths=[85,150,85,150]
        )

        personal_table.setStyle(
            TableStyle([
                ("BACKGROUND",(0,0),(0,-1),colors.HexColor("#D9ECFF")),
                ("BACKGROUND",(2,0),(2,-1),colors.HexColor("#D9ECFF")),
                ("BACKGROUND",(1,0),(1,-1),colors.whitesmoke),
                ("BACKGROUND",(3,0),(3,-1),colors.whitesmoke),
                ("GRID",(0,0),(-1,-1),0.5,colors.lightgrey),
                ("BOX",(0,0),(-1,-1),1,colors.grey),
                ("FONTNAME",(0,0),(0,-1),"Helvetica-Bold"),
                ("FONTNAME",(2,0),(2,-1),"Helvetica-Bold"),
                ("BOTTOMPADDING",(0,0),(-1,-1),8),
                ("TOPPADDING",(0,0),(-1,-1),8),
                ("VALIGN",(0,0),(-1,-1),"MIDDLE")
            ])
        )

        elements.append(
            personal_table
        )

        elements.append(
            Spacer(1,18)
        )







        # ==================================================
        # SCHOOL EDUCATION
        # ==================================================

        elements.append(
            Paragraph(
                "SCHOOL EDUCATION",
                self.heading_style
            )
        )

        school_data = [
            [
                "Level",
                "School",
                "Board",
                "Academic Year",
                "Grade"
            ]
        ]

        for record in report["school"]:
            school_data.append(
                [
                    record["level"],
                    record["organization"],
                    record["category"],
                    record["academic_year"],
                    str(record["grade"])
                ]
            )

        school_table = Table(
            school_data,
            colWidths=[60,170,70,110,60]
        )

        school_table.setStyle(
            self.table_style(
                colors.darkgreen
            )
        )

        elements.append(
            school_table
        )

        elements.append(
            Spacer(1,20)
        )









        # ==================================================
        # COLLEGE EDUCATION
        # ==================================================

        elements.append(
            Paragraph(
                "COLLEGE EDUCATION",
                self.heading_style
            )
        )

        for degree in report["college"]:
            elements.append(
                Paragraph(
                    f"<b>{report['college'].index(degree)+1}. "
                    f"{degree['degree']} | "
                    f"{degree['college']} | "
                    f"{degree['branch']}</b>",
                    self.normal_style
                )
            )

            elements.append(
                Spacer(1,8)
            )


            semester_data = [
                [
                    "Semester",
                    "Credits",
                    "SGPA",
                    "Academic Year"
                ]
            ]

            for semester in degree["semesters"]:
                semester_data.append(
                    [
                        semester["level"],
                        str(semester["total_credit"]),
                        str(semester["sgpa"]),
                        semester["academic_year"]
                    ]
                )

            semester_data.append(
                [
                    "Total Credit",
                    str(degree["total_credit"]),
                    "CGPA",
                    str(degree["cgpa"])
                ]
            )

            semester_table = Table(
                semester_data,
                colWidths=[120,90,90,170]
            )

            style = self.table_style(colors.darkblue)
            last = len(semester_data) - 1

            style.add(
                "BACKGROUND",
                (0,last),
                (-1,last),
                colors.HexColor("#FFE7B3")
            )

            style.add(
                "FONTNAME",
                (0,last),
                (-1,last),
                "Helvetica-Bold"
            )

            semester_table.setStyle(style)


            elements.append(
                semester_table
            )

            elements.append(
                Spacer(1,20)
            )








        # ------------------------------------------------
        # Remaining PDF content will be added here
        # ------------------------------------------------

        # Build PDF
        doc.build(
            elements,
            onFirstPage=self.add_footer,
            onLaterPages=self.add_footer
        )
        pdf = buffer.getvalue()
        buffer.close()

        return pdf